### ISSUE TITLE
Don't know how to use the function `write-file`

### ISSUE THREAD

**Issue by stardiviner** [gfredericks/org-editor#1]
I don't understand how to use the function `write-file` in org-editor, how to pass arguments to it? Can you give out an example?
Even though I read the source code:
```
(defn write-file
  [writer file]
  (with-open [pw (java.io.PrintWriter. writer)]
    (binding [*out* pw]
      ((fn func [{::keys [prelude sections]}]
         (run! println prelude)
         (doseq [section sections]
           (println (::header section))
           (func section)))
       file))))
```
Still confused.
When I try `(orgmode/write-file <org-editor-map> "notes.org")`. It still report error:
```
Exception in thread "main" java.lang.IllegalArgumentException: No matching ctor found for class java.io.PrintWriter, compiling:(/home/stardiviner/Documents/learning/Clojure/kindle-export-notes/target/080ed0e961791538a4154f3d9542d01804cc50f2-init.clj:1:5)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.Compiler.loadFile(Compiler.java:7452)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$init_opt.invokeStatic(main.clj:280)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invokeStatic(main.clj:311)
        at clojure.main$null_opt.invokeStatic(main.clj:345)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
```

Don't understand why use `java.io.PrintWriter`. and use `print` to write output to file.

I have a feature request, add support write properties to file in function `write-file`. WDYT?

**Comment by gfredericks** [comment]
I added an explicit example here: https://github.com/gfredericks/org-editor/commit/4da7c6b1f2537d90659fe6a16e02a8f0deb3687d

You don't have to call print, you only call write-file once.

I think you just had the args backwards.

I'm not sure what you mean by "add support write properties to file in function `write-file`"; can you give an example of what data you would pass and how it would look in the org file?

**Comment by stardiviner** [comment]
Thanks for the example, because I'm confused by your function `write-file`'s second parameter `file`. I thought is will be a filename string,..... That's why I asked this question.

About `add support for writing properties to org file`, like this:
```
(write-file "output3.org"
              {:prelude  '("You can have lines"
                           "before the first"
                           ""
                           "heading"
                           ""),
               :sections [{:header     "* Heading 1",
                           :properties [{:author "kk"
                                         :date   "[2018-09-04 Sat]"}]
                           :prelude    '("  A few"
                                         ""
                                         "  lines here"),
                           :sections   [{:header  "** Heading 1a",
                                         :prelude '(),}]}]}
              )
```
```org
You can have lines
before the first

heading

* Heading 1
     :PROPERTIES:
     :AUTHOR:   kk
     :DATE: [2018-09-06 Thu]
     :END:

A few lines here.

** Heading 1a

```

**Comment by gfredericks** [comment]
Yeah I think I need a better word than `file` to describe the top-level data structure.

Maybe I should add specs for documentation.

In any case, the properties idea I've thought about some. Are you familiar with how `read-properties`, `prop-get` and `prop-assoc` work? Are those sufficient for what you want to do, and you'd just rather have something more direct?

The main thing that makes me hesitant is that the properties could then appear in two places -- in the properties key, and in the prelude. I've tried to make the core data structure so simple that it can't be wrong, and then have a variety of functions for manipulating it.

**Comment by stardiviner** [comment]
> Yeah I think I need a better word than file to describe the top-level data structure.
maybe parameter named like `data-map`?

I can get a probable understanding what they do of `read-properties` etc functions. But not simple for a newbie programmer me.

Here is my code to use org-editor and kce-clip to export Kindle clips to Org Mode file. I don't know how to use `prop-assoc` in my code.

```clojure
(ns kindle-export-notes.core
  (:require [clojure.pprint])
  (:require [clojure.java.io])
  (:require [kce-clj.core :as kindle])
  (:require [com.gfredericks.org-editor :as orgmode])
  (:import java.text.DateFormat)
  (:import java.text.SimpleDateFormat))

;;; parse Kindle clips file.
(defn- read-clips
  []
  (with-open [f (clojure.java.io/reader "/home/stardiviner/Documents/learning/Clojure/kindle-export-notes/My Clippings.txt")]
    (kindle/extract f "UTC")))

;;; convert kce-clj clips result map into org-editor read-in map.
(defn- destructure-clip-to-org
  "Destructure Kindle clips map structure into kce-clj Org Mode format map structure."
  [clips]
  (map
   (fn [clip]
     (let [{headline           :title
            prelude            :text
            property-author    :author
            property-category  :category
            property-page      :page
            property-location  :location
            property-timestamp :timestamp}
           clip]
       {:header  (list headline)
        :prelude (list prelude)
        ;; TODO: add properties
        ;; :properties {:author    property-author
        ;;              :category  property-category
        ;;              :page      property-page
        ;;              :location  property-location
        ;;              :timestamp property-timestamp}
        }))
   clips))

(defn- merge-same-book-notes
  "Merge same book  notes together."
  [clips]
  (for [[k vs] (group-by :header clips)]
    {:header  (str "* " (first k))
     :prelude (concat
               (mapv
                #(-> %
                     :prelude
                     first
                     (->> (format "\n#+begin_quote\n%s\n#+end_quote\n")))
                vs))}))

(def ^:private org-editor-map
  {:sections (into []
                   (-> (read-clips)
                       destructure-clip-to-org
                       merge-same-book-notes))})


(defn write-file
  [file maps]
  (with-open [pw (clojure.java.io/writer file :append true)]
    ;; [pw (java.io.PrintWriter. writer :append true)]
    (binding [*out* pw]
      ((fn func [{:keys [prelude sections]}]
         (run! println prelude)
         (doseq [section sections]
           (println (:header section))
           (func section)))
       maps))))

;; test with writing properties
(comment
  (orgmode/write-file "output3.org"
                      {:prelude  '("You can have lines"
                                   "before the first"
                                   ""
                                   "heading"
                                   ""),
                       :sections [{:header   "* Heading 1",
                                   ;; :properties [{:author "kk"
                                   ;;               :date   "[2018-09-04 Sat]"}]
                                   :prelude  '("  A few"
                                               ""
                                               "  lines here"),
                                   :sections [{:header  "** Heading 1a",
                                               :prelude '(),}]}]}
                      ))

(defn -main []
  ;; check out the `org-editor-map` data structure result.
  (binding [*out* (clojure.java.io/writer "output")]
    (clojure.pprint/pprint org-editor-map))

  ;; write to Org Mode file.
  ;; (orgmode/write-file "notes.org" org-editor-map)
  ;; NOTE: because `orgmode/write-file` use namespaced ::key.
  (write-file "notes.org" org-editor-map)
  )
```

**Comment by gfredericks** [comment]
A couple notes

1) the keys in the maps need to be namespaced keywords, such as `:com.gfredericks.org-editor/header` -- the examples in the readme use clojure's new syntax for prefixing all keywords in a map
2) `prop-assoc` is used to modify the `::prelude` key; e.g., inside of `destructure-clip-to-org` you could have something like:

``` clojure
(map
 (fn [clip]
   (let [...]
     (reduce-kv prop-assoc
                #:com.gfredericks.org-editor
                {:header "something"
                 :prelude []
                 :sections []}
                [["author" property-author]
                 ...]))))
```

I hope that helps.

**Comment by stardiviner** [comment]
This works. Thanks.
